version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/miekg/dns
    versions:
    - 1.1.35
    - 1.1.38
  rebase-strategy: disabled
