language: go
os:
- linux
- osx
go:
- '1.12'
script:
- make test
before_deploy:
- make PACKAGE="lpc-${TRAVIS_TAG}-${TRAVIS_OS_NAME}" package
deploy:
  provider: releases
  api_key:
    secure: k72L6dhncTHG5382FAf0wxkfXUSoHPSXw2gt2kAtJR0W7n49ri7Wc4k6/MsjPN1WO/5ckBYsreIsyk9tcMoya8lBKr/Ltavpj+zhBZcBG0ql+gH837tmVIsPHMpcdyFSEjOQxAOdxpv2PSSrMlfxWi9BNT1gdZiX7f6/m7qIzC5tOis7TZF1nQq2nPtOJryim5IH3wqhZ9aVr0WJrXKJk4s/957da8UdNQX3F1X62ScOJ9SeIVqskQum1mvhwvoHbAa3SZExA2hBJIzNPKIDdEeqByS9P2KCH33V5SiGuWKsqRIFNkcw9JR8QT9/dzko8EU++OwB+yoNOPIiDeoLV1zU1FEpPaWfXQtIE3Pak3sDFGGUv36PmLUmr7JdywRPS+3sshzdyWv16EAUYAu3RoihcsCEE71jQYT39ZdDOTUlkZ4Hp8utPXqOb7Us6yVuN7p2o6kcVwdp7ac0kBdRqQbIJdovlM13ZPwPgJp5o0XnnYvFTQqWwIDOVwVhInrOmWAPTbEEL/gLC6GnwFjGupgvMmQmQGpVVRzSaIwfS5zvj2+JnzJXngZXJmcBvxRzciHXN7IIj3rU6T42LcnvIn6pkDkeT9GbSAgZ58sCkFvXGosQiIUfaIFqgmf5hgPg/50LfjTP5p5iTn5IW3vGVHaBmOQsW9ABCs1TsjB12A8=
  file: "lpc-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz"
  skip_cleanup: true
  on:
    repo: mys721tx/lpc
    tags: true
